name: pushandpull-prod

services:
  pushandpull-redis:
    container_name: pushandpull-redis

  pushandpull-server:
    container_name: pushandpull-server
    ports:
      - "21754:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=${DB_CONNECTION_STRING}
