name: pushandpull-stage

services:
  pushandpull-db:
    image: postgres:17
    container_name: pushandpull-stage-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pushandpull-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pushandpull-redis:
    container_name: pushandpull-stage-redis

  pushandpull-server:
    image: seanyee1227/pushandpull-server:stage
    container_name: pushandpull-stage-server
    ports:
      - "80:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ConnectionStrings__Default=Host=pushandpull-db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password='${POSTGRES_PASSWORD}'
      - ReverseProxy__KnownProxyIp=${CADDY_PROXY_IP}
    depends_on:
      pushandpull-db:
        condition: service_healthy

volumes:
  postgres_data:
    external: true
    name: pushandpull-stage-postgres-data
